'use client';

import { useEffect, useRef, useState } from 'react';
import { Brain, Loader2, RefreshCw, ShieldCheck, TriangleAlert } from 'lucide-react';
import { Card, CardLabel, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { TierBadge } from '@/components/shared/tier-badge';
import {
  apiClient,
  ApiError,
  VERDICT_LABELS,
  type AnalystResponse,
  type AnalystAssessment,
  type AnalystEvidenceItem,
  type Tier,
} from '@/lib/api';

const POLL_INTERVAL_MS = 2000;
const MAX_POLLS = 10;

/**
 * Minimum UI to exercise the Omi Analyst endpoint (Sprint 001).
 * POST -> 503 (disabled) | 202 (generating -> poll) | 200 (assessment).
 * The assessment is a recommendation bounded by the engine's evidence; it never
 * recomputes a score. Off by default — the disabled state degrades gracefully.
 */
export function AnalystPanel({ slug }: { slug: string }) {
  const [assessment, setAssessment] = useState<AnalystAssessment | null>(null);
  const [provider, setProvider] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const pollRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => () => { if (pollRef.current) clearTimeout(pollRef.current); }, []);

  const post = (refresh: boolean) =>
    apiClient<AnalystResponse>(
      `/v1/investigations/${slug}/analyst${refresh ? '?refresh=true' : ''}`,
      { method: 'POST' },
    );

  const run = async (refresh: boolean) => {
    setError(null);
    setDisabled(false);
    setPending(true);
    let polls = 0;

    const step = async (doRefresh: boolean): Promise<void> => {
      try {
        const r = await post(doRefresh);
        if (r.status === 'ready' && r.assessment) {
          setAssessment(r.assessment);
          setProvider(r.provider ?? null);
          setPending(false);
          return;
        }
        // Still generating off the request hot path — poll (no refresh) until ready.
        if (polls++ >= MAX_POLLS) {
          setError('Assessment is taking longer than expected. Try again shortly.');
          setPending(false);
          return;
        }
        pollRef.current = setTimeout(() => { void step(false); }, POLL_INTERVAL_MS);
      } catch (e) {
        if (e instanceof ApiError && e.status === 503) {
          setDisabled(true);
        } else {
          setError(e instanceof ApiError ? e.message : 'Failed to generate the assessment.');
        }
        setPending(false);
      }
    };

    await step(refresh);
  };

  return (
    <Card>
      <div className="flex items-center justify-between gap-2 mb-2 flex-wrap">
        <CardLabel className="m-0 flex items-center gap-1.5">
          <Brain size={11} /> Omi Analyst assessment
        </CardLabel>
        {provider && (
          <span
            className="font-mono text-2xs tracking-wider uppercase text-accent"
            title={`Generated by ${provider}`}
          >
            ▸ {provider.replace(/->fallback:.*/, ' → fallback').replace(/-v1$/, '')}
          </span>
        )}
      </div>

      {disabled ? (
        <p className="text-sm text-fg-dim flex items-start gap-2">
          <TriangleAlert size={14} className="mt-0.5 shrink-0 text-fg-mute" />
          Omi Analyst reasoning isn&apos;t enabled on this server yet. The structured,
          evidence-bounded assessment becomes available once the reasoning layer is
          turned on — the investigation evidence above is unaffected.
        </p>
      ) : !assessment ? (
        <>
          <CardTitle>No assessment yet</CardTitle>
          <p className="text-sm text-fg-dim mb-4 max-w-xl">
            Generate the Omi Analyst&apos;s structured reading of this investigation —
            a recommended verdict with calibrated confidence, the evidence for and
            against, and what would change the conclusion. It interprets the evidence
            the engine already produced; it never recomputes a score.
          </p>
          <Button onClick={() => run(false)} disabled={pending}>
            {pending ? <><Loader2 size={14} className="animate-spin" /> Reasoning…</> : <><Brain size={14} /> Generate assessment</>}
          </Button>
        </>
      ) : (
        <AssessmentView a={assessment} pending={pending} onRefresh={() => run(true)} />
      )}

      {error && (
        <p className="mt-3 text-xs text-danger bg-danger/10 border border-danger/40 rounded-sm px-3 py-2 font-mono">
          {error}
        </p>
      )}
    </Card>
  );
}

function pct(x: number): string {
  return `${Math.round((x ?? 0) * 100)}%`;
}

function verdictLabel(v: string): string {
  return (VERDICT_LABELS as Record<string, string>)[v] ?? v;
}

function AssessmentView({
  a, pending, onRefresh,
}: { a: AnalystAssessment; pending: boolean; onRefresh: () => void }) {
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3 flex-wrap">
        <TierBadge tier={a.suspicion_tier as Tier} />
        <span className="font-mono text-2xs tracking-wider uppercase text-fg-mute border border-border-hot px-2.5 py-1 rounded-full bg-bg-elev-2">
          {verdictLabel(a.verdict)} · recommended
        </span>
        <span className="font-mono text-2xs tracking-wider uppercase text-fg-mute">
          {pct(a.suspicion_probability)} suspicion · {a.confidence_band} confidence
        </span>
      </div>

      {a.headline && <p className="text-sm text-fg leading-relaxed">{a.headline}</p>}
      {a.assessment && (
        <p className="text-sm text-fg-dim leading-relaxed whitespace-pre-line">{a.assessment}</p>
      )}

      <div className="grid sm:grid-cols-2 gap-4">
        <EvidenceList label="Evidence for" tone="raise" items={a.evidence_for} />
        <EvidenceList label="Evidence against" tone="lower" items={a.evidence_against} />
      </div>

      <PlainList label="Confidence & uncertainty" lead={a.confidence_rationale} items={a.uncertainty} />
      <PlainList label="What would change this" items={a.what_would_change_this} />

      {a.governance && (
        <p className="text-2xs font-mono text-fg-mute flex items-center gap-1.5 flex-wrap">
          <ShieldCheck size={11} className="text-accent shrink-0" />
          Governor {a.governance.verdict ?? 'n/a'} · {a.governance.provider ?? 'floor'}
          {typeof a.governance.latency_ms === 'number' ? ` · ${Math.round(a.governance.latency_ms)}ms` : ''}
        </p>
      )}
      {a.limits_statement && (
        <p className="text-2xs text-fg-faint border-t border-border-1/60 pt-3 leading-relaxed">
          {a.limits_statement}
        </p>
      )}

      <Button variant="secondary" size="sm" onClick={onRefresh} disabled={pending}>
        {pending ? <><Loader2 size={12} className="animate-spin" /> Regenerating…</> : <><RefreshCw size={12} /> Regenerate</>}
      </Button>
    </div>
  );
}

function EvidenceList({
  label, tone, items,
}: { label: string; tone: 'raise' | 'lower'; items: AnalystEvidenceItem[] }) {
  return (
    <div>
      <CardLabel className="mb-2">{label}</CardLabel>
      {items && items.length > 0 ? (
        <ul className="space-y-1.5">
          {items.map((it, i) => (
            <li key={i} className="text-xs text-fg-dim flex gap-2 leading-relaxed">
              <span className={tone === 'raise' ? 'text-danger' : 'text-accent'}>
                {tone === 'raise' ? '▲' : '▼'}
              </span>
              <span>
                <span className="text-fg-mute font-mono">{it.signal}</span> — {it.claim}
              </span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-xs text-fg-faint">None reported.</p>
      )}
    </div>
  );
}

function PlainList({
  label, lead, items,
}: { label: string; lead?: string; items: string[] }) {
  if (!lead && (!items || items.length === 0)) return null;
  return (
    <div>
      <CardLabel className="mb-2">{label}</CardLabel>
      {lead && <p className="text-xs text-fg-dim mb-1.5 leading-relaxed">{lead}</p>}
      {items && items.length > 0 && (
        <ul className="space-y-1 list-disc pl-4">
          {items.map((s, i) => (
            <li key={i} className="text-xs text-fg-dim leading-relaxed">{s}</li>
          ))}
        </ul>
      )}
    </div>
  );
}
