'use client';

import { useEffect, useRef, useState } from 'react';
import { Brain, Loader2, ShieldCheck, TriangleAlert } from 'lucide-react';
import { Card, CardLabel } from '@/components/ui/card';
import { TierBadge } from '@/components/shared/tier-badge';
import { ProbabilityBar } from '@/components/shared/probability-bar';
import {
  apiClient,
  ApiError,
  VERDICT_LABELS,
  type AnalystResponse,
  type AnalystAssessment,
  type AnalystEvidenceItem,
  type ComprehensiveSection,
  type ComprehensiveSections,
  type Tier,
} from '@/lib/api';

const POLL_INTERVAL_MS = 2000;
const MAX_POLLS = 10;

/**
 * Minimum UI to exercise the Omi Analyst endpoint (Sprint 001).
 * POST -> 503 (disabled) | 202 (generating -> poll) | 200 (assessment).
 * The assessment is a recommendation bounded by the engine's evidence; it never
 * recomputes a score. Off by default — the disabled state degrades gracefully.
 */
export function AnalystPanel({ slug }: { slug: string }) {
  const [assessment, setAssessment] = useState<AnalystAssessment | null>(null);
  const [provider, setProvider] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const pollRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => () => { if (pollRef.current) clearTimeout(pollRef.current); }, []);

  const post = (refresh: boolean) =>
    apiClient<AnalystResponse>(
      `/v1/investigations/${slug}/analyst${refresh ? '?refresh=true' : ''}`,
      { method: 'POST' },
    );

  const run = async (refresh: boolean) => {
    setError(null);
    setDisabled(false);
    setPending(true);
    let polls = 0;

    const step = async (doRefresh: boolean): Promise<void> => {
      try {
        const r = await post(doRefresh);
        if (r.status === 'ready' && r.assessment) {
          setAssessment(r.assessment);
          setProvider(r.provider ?? null);
          setPending(false);
          return;
        }
        // Still generating off the request hot path — poll (no refresh) until ready.
        if (polls++ >= MAX_POLLS) {
          setError('Assessment is taking longer than expected. Try again shortly.');
          setPending(false);
          return;
        }
        pollRef.current = setTimeout(() => { void step(false); }, POLL_INTERVAL_MS);
      } catch (e) {
        if (e instanceof ApiError && e.status === 503) {
          setDisabled(true);
        } else {
          setError(e instanceof ApiError ? e.message : 'Failed to generate the assessment.');
        }
        setPending(false);
      }
    };

    await step(refresh);
  };

  // Auto-load on mount: the analyst now runs server-side for every investigation
  // (scheduled at scan time), so surface its cached assessment automatically — the AI
  // reading is part of the report, not a manual action. A cached result returns
  // immediately (no new model call); 503 degrades to the graceful "not enabled" notice.
  useEffect(() => {
    void run(false);
    // Fire once per investigation; `run` is stable for the component's lifetime.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug]);

  return (
    <Card>
      <div className="flex items-center justify-between gap-2 mb-2 flex-wrap">
        <CardLabel className="m-0 flex items-center gap-1.5">
          <Brain size={11} /> Omi Analyst assessment
        </CardLabel>
        {provider && (
          <span
            className="font-mono text-2xs tracking-wider uppercase text-accent"
            title={`Generated by ${provider}`}
          >
            ▸ {provider.replace(/->fallback:.*/, ' → fallback').replace(/-v1$/, '')}
          </span>
        )}
      </div>

      {disabled ? (
        <p className="text-sm text-fg-dim flex items-start gap-2">
          <TriangleAlert size={14} className="mt-0.5 shrink-0 text-fg-mute" />
          Omi Analyst reasoning isn&apos;t enabled on this server yet. The structured,
          evidence-bounded assessment becomes available once the reasoning layer is
          turned on — the investigation evidence above is unaffected.
        </p>
      ) : !assessment ? (
        // The analyst runs automatically for every investigation — no manual generation.
        // Surface the in-progress / pending state; the assessment fills in when ready.
        <p className="text-sm text-fg-dim flex items-start gap-2">
          <Loader2 size={14} className={`mt-0.5 shrink-0 text-fg-mute${pending ? ' animate-spin' : ''}`} />
          {pending
            ? 'Reasoning over the investigation evidence…'
            : 'The Omi Analyst’s structured reading of this investigation will appear here. It interprets the evidence the engine already produced; it never recomputes a score.'}
        </p>
      ) : (
        <AssessmentView a={assessment} />
      )}

      {error && (
        <p className="mt-3 text-xs text-danger bg-danger/10 border border-danger/40 rounded-sm px-3 py-2 font-mono">
          {error}
        </p>
      )}
    </Card>
  );
}

function verdictLabel(v: string): string {
  return (VERDICT_LABELS as Record<string, string>)[v] ?? v;
}

// The corroboration methods, and which of them are DISCRIMINATIVE of coordination (a maximal
// 'coordinated' read requires >=1 discriminative method AND single_axis_capped === false). Mirrors
// the backend gate — surfaced here so the panel shows WHY a coordinated read is (or isn't) permitted.
const METHOD_LABELS: Record<string, string> = {
  fingerprint_cluster: 'fingerprint',
  co_engagement: 'co-engagement',
  co_tag: 'co-tag',
  temporal_semantic: 'temporal+semantic',
  style_match: 'style match',
  age_cohort: 'age cohort',
  reply_pods: 'reply pods',
};
const DISCRIMINATIVE_METHODS = new Set(['fingerprint_cluster', 'co_engagement', 'co_tag']);

// The engine's corroboration state (echoed onto the assessment). Rendered as structured chips — the
// discriminative methods that fired, plus the single-axis-cap and convergence flags — so the reader
// can see the coordination gate directly instead of inferring it from prose.
function CorroborationStrip({ corr }: { corr?: AnalystAssessment['corroboration'] }) {
  if (!corr) return null;
  const methods = corr.discriminative_methods ?? [];
  return (
    <div className="flex items-center gap-1.5 flex-wrap font-mono text-2xs">
      <span className="uppercase tracking-wider text-fg-mute">Corroboration</span>
      {methods.length > 0 ? (
        methods.map((m) => (
          <span
            key={m}
            className={`rounded-full border px-1.5 py-0.5 ${
              DISCRIMINATIVE_METHODS.has(m)
                ? 'border-accent/50 text-accent'
                : 'border-border-1/60 text-fg-mute'
            }`}
          >
            {METHOD_LABELS[m] ?? m}
          </span>
        ))
      ) : (
        <span className="text-fg-faint">no discriminative method fired</span>
      )}
      {corr.single_axis_capped && (
        <span
          className="rounded-full border border-tier-moderate/40 text-tier-moderate px-1.5 py-0.5"
          title="One axis carried the score; the coordinated read is capped."
        >
          single-axis capped
        </span>
      )}
      {corr.convergence && (
        <span
          className="rounded-full border border-border-1/60 text-fg-mute px-1.5 py-0.5"
          title="Two or more independent detectors converged."
        >
          convergence
        </span>
      )}
    </div>
  );
}

// Supplemental signals (e.g. AI-writing) — reported as neutral context that carries ZERO suspicion
// weight. Surfaced as its own labeled block so it can never be mistaken for incriminating evidence.
function SupplementalContext({ items }: { items?: { signal: string; note: string }[] }) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <CardLabel className="mb-2">Context · zero suspicion weight</CardLabel>
      <ul className="space-y-1.5">
        {items.map((it, i) => (
          <li key={i} className="text-xs text-fg-dim flex gap-2 leading-relaxed">
            <span className="text-fg-mute">◇</span>
            <span>
              <span className="text-fg-mute font-mono">{it.signal}</span> — {it.note}
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// The explicit legitimate-coordination hypothesis the analyst considered (precision-frontier
// discipline). Present for coordination reads; surfaced verbatim from the structured field.
function LegitimateHypothesis({ text }: { text?: string | null }) {
  if (!text) return null;
  return (
    <div>
      <CardLabel className="mb-2">Legitimate-coordination hypothesis</CardLabel>
      <p className="text-xs text-fg-dim leading-relaxed">{text}</p>
    </div>
  );
}

// Whether Mistral actually authored this assessment. Prefer the explicit trace flag; fall back to the
// governance provider string for assessments persisted before the trace existed. When false, the
// synthesis prose is the deterministic Floor's — it must NEVER be shown as AI reasoning.
function isModelBacked(a: AnalystAssessment): boolean {
  if (typeof a.investigation_trace?.model_backed === 'boolean') return a.investigation_trace.model_backed;
  const provider = a.governance?.provider ?? '';
  return provider.length > 0 && !/fallback|deterministic|floor/i.test(provider);
}

function AssessmentView({ a }: { a: AnalystAssessment }) {
  // Product-cutover rule: only Mistral-authored assessments render as AI reasoning. If the model was
  // not reached, the deterministic Floor stood in — we must NOT present its synthesized verdict /
  // headline / assessment / evidence as though Mistral wrote it.
  if (!isModelBacked(a)) return <AiUnavailable a={a} />;

  return (
    <div className="space-y-5">
      {/* ── LEAD INVESTIGATOR SYNTHESIS (Mistral) ─────────────────────────── */}
      <div className="space-y-4">
        <div className="flex items-center gap-3 flex-wrap">
          <TierBadge tier={a.suspicion_tier as Tier} />
          <span className="font-mono text-2xs tracking-wider uppercase text-fg-mute border border-border-hot px-2.5 py-1 rounded-full bg-bg-elev-2">
            {verdictLabel(a.verdict)} · recommended
          </span>
          <span className="font-mono text-2xs tracking-wider uppercase text-fg-mute">
            {a.confidence_band} confidence
          </span>
          {a.coordination_label && (
            <span className="font-mono text-2xs tracking-wider uppercase text-fg-mute border border-border-1/60 px-2.5 py-1 rounded-full bg-bg-elev-2">
              coordination: {a.coordination_label}
            </span>
          )}
        </div>

        {/* Suspicion probability — the echoed engine number, as a tier-colored bar (not bare text). */}
        <div className="flex items-center gap-2">
          <span className="font-mono text-2xs uppercase tracking-wider text-fg-mute w-16 shrink-0">
            suspicion
          </span>
          <ProbabilityBar
            value={a.suspicion_probability}
            tier={a.suspicion_tier as Tier}
            className="flex-1"
          />
        </div>

        <CorroborationStrip corr={a.corroboration} />

        {a.headline && <p className="text-sm text-fg leading-relaxed">{a.headline}</p>}
        {a.assessment && (
          <p className="text-sm text-fg-dim leading-relaxed whitespace-pre-line">{a.assessment}</p>
        )}

        <div className="grid sm:grid-cols-2 gap-4">
          <EvidenceList label="Evidence for" tone="raise" items={a.evidence_for} />
          <EvidenceList label="Evidence against" tone="lower" items={a.evidence_against} />
        </div>

        <PlainList label="Confidence & uncertainty" lead={a.confidence_rationale} items={a.uncertainty} />
        <PlainList label="What would change this" items={a.what_would_change_this} />
        <SupplementalContext items={a.supplemental_context} />
        <LegitimateHypothesis text={a.legitimate_hypothesis} />
      </div>

      {/* ── DOMAIN REASONING (six views over the ONE comprehensive response) ── */}
      <DomainReasoning
        sections={a.comprehensive_sections}
        validation={a.comprehensive_validation}
      />

      {a.governance && (
        <p className="text-2xs font-mono text-fg-mute flex items-center gap-1.5 flex-wrap">
          <ShieldCheck size={11} className="text-accent shrink-0" />
          Governor {a.governance.verdict ?? 'n/a'} · {a.governance.provider ?? 'floor'}
          {typeof a.governance.latency_ms === 'number' ? ` · ${Math.round(a.governance.latency_ms)}ms` : ''}
        </p>
      )}
      {a.limits_statement && (
        <p className="text-2xs text-fg-faint border-t border-border-1/60 pt-3 leading-relaxed">
          {a.limits_statement}
        </p>
      )}
    </div>
  );
}

// AI reasoning was not produced by Mistral (endpoint unreachable / not enabled). We surface an honest
// notice and DO NOT render the deterministic Floor's synthesized verdict/headline/assessment/evidence
// as AI. The deterministic evidence + measurements remain available elsewhere on the page.
function AiUnavailable({ a }: { a: AnalystAssessment }) {
  return (
    <div className="text-sm text-fg-dim flex items-start gap-2">
      <TriangleAlert size={14} className="mt-0.5 shrink-0 text-fg-mute" />
      <span>
        AI reasoning is not available for this investigation yet — the reasoning model wasn’t reached,
        so Mistral’s interpretation could not be produced. The deterministic evidence and measurements
        on this page are unaffected.
        {a.governance?.provider && (
          <span className="block mt-1 text-2xs font-mono text-fg-faint">
            provider: {a.governance.provider}
          </span>
        )}
      </span>
    </div>
  );
}

const DOMAIN_PANELS: { key: keyof ComprehensiveSections; title: string }[] = [
  { key: 'comment_reasoning', title: 'Comment analysis' },
  { key: 'commenter_history_reasoning', title: 'Commenter history' },
  { key: 'account_reasoning', title: 'Account analysis' },
  { key: 'narrative_reasoning', title: 'Narrative analysis' },
  { key: 'coordination_reasoning', title: 'Coordination analysis' },
  { key: 'campaign_reasoning', title: 'Campaign analysis' },
];

// The six per-domain reasoning sections of the single comprehensive Mistral response. Each panel is a
// pure view over the already-loaded assessment — expanding a panel triggers NO request (no per-panel
// inference). Sections the model left empty are shown as "no reasoning provided" rather than hidden.
function DomainReasoning({
  sections,
  validation,
}: {
  sections?: ComprehensiveSections;
  validation?: AnalystAssessment['comprehensive_validation'];
}) {
  const present = DOMAIN_PANELS.filter(({ key }) => sections?.[key] !== undefined);
  if (present.length === 0) return null;
  return (
    <div className="border-t border-border-1/60 pt-4 space-y-2">
      <CardLabel className="flex items-center gap-1.5">
        <Brain size={11} /> Domain reasoning · one AI investigation
      </CardLabel>
      <div className="space-y-1.5">
        {present.map(({ key, title }) => (
          <DomainPanel
            key={key}
            title={title}
            section={sections?.[key]}
            unresolved={validation?.sections?.[key]?.unresolved}
          />
        ))}
      </div>
    </div>
  );
}

function DomainPanel({
  title,
  section,
  unresolved,
}: {
  title: string;
  section?: ComprehensiveSection;
  unresolved?: string[];
}) {
  const text = section?.assessment?.trim();
  const citations = section?.citations ?? [];
  const unresolvedSet = new Set(unresolved ?? []);
  return (
    <details className="group rounded-sm border border-border-1/60 bg-bg-elev-2/40 open:bg-bg-elev-2">
      <summary className="cursor-pointer select-none list-none px-3 py-2 text-xs font-mono uppercase tracking-wider text-fg-mute flex items-center justify-between gap-2">
        <span>{title}</span>
        <span className="text-fg-faint text-2xs group-open:hidden">expand</span>
        <span className="text-fg-faint text-2xs hidden group-open:inline">collapse</span>
      </summary>
      <div className="px-3 pb-3 space-y-2">
        {text ? (
          <p className="text-xs text-fg-dim leading-relaxed whitespace-pre-line">{text}</p>
        ) : (
          <p className="text-xs text-fg-faint italic">No reasoning provided for this domain.</p>
        )}
        {citations.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {citations.map((c, i) => {
              const bad = unresolvedSet.has(c);
              return (
                <span
                  key={i}
                  title={bad ? 'This citation does not resolve against the evidence.' : undefined}
                  className={`font-mono text-2xs rounded-full border px-1.5 py-0.5 ${
                    bad
                      ? 'text-danger border-danger/50 line-through'
                      : 'text-fg-mute border-border-1/60'
                  }`}
                >
                  {c}
                </span>
              );
            })}
          </div>
        )}
      </div>
    </details>
  );
}

// Direction is echoed from the detector contribution (raises / lowers / neutral). Prefer the
// structured field; fall back to the column's tone only when the model omitted it.
function directionMark(
  direction: AnalystEvidenceItem['direction'],
  tone: 'raise' | 'lower',
): { sym: string; cls: string } {
  const d = direction ?? (tone === 'raise' ? 'raises' : 'lowers');
  if (d === 'raises') return { sym: '▲', cls: 'text-danger' };
  if (d === 'lowers') return { sym: '▼', cls: 'text-accent' };
  return { sym: '•', cls: 'text-fg-mute' };
}

function EvidenceList({
  label, tone, items,
}: { label: string; tone: 'raise' | 'lower'; items: AnalystEvidenceItem[] }) {
  return (
    <div>
      <CardLabel className="mb-2">{label}</CardLabel>
      {items && items.length > 0 ? (
        <ul className="space-y-2">
          {items.map((it, i) => {
            const mark = directionMark(it.direction, tone);
            return (
              <li key={i} className="text-xs text-fg-dim leading-relaxed">
                <div className="flex gap-2">
                  <span className={mark.cls}>{mark.sym}</span>
                  <span>
                    <span className="text-fg-mute font-mono">{it.signal}</span> — {it.claim}
                  </span>
                </div>
                {/* impact = the detector's share of total score movement (echoed) — shown as a bar. */}
                {typeof it.impact === 'number' && (
                  <div className="mt-1 pl-5 max-w-[180px]">
                    <ProbabilityBar value={it.impact} size="sm" />
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      ) : (
        <p className="text-xs text-fg-faint">None reported.</p>
      )}
    </div>
  );
}

function PlainList({
  label, lead, items,
}: { label: string; lead?: string; items: string[] }) {
  if (!lead && (!items || items.length === 0)) return null;
  return (
    <div>
      <CardLabel className="mb-2">{label}</CardLabel>
      {lead && <p className="text-xs text-fg-dim mb-1.5 leading-relaxed">{lead}</p>}
      {items && items.length > 0 && (
        <ul className="space-y-1 list-disc pl-4">
          {items.map((s, i) => (
            <li key={i} className="text-xs text-fg-dim leading-relaxed">{s}</li>
          ))}
        </ul>
      )}
    </div>
  );
}
