'use client';

import { useState } from 'react';
import { Sparkles, RefreshCw, Loader2 } from 'lucide-react';
import { Card, CardLabel, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { apiClient, ApiError, type CommentaryResponse } from '@/lib/api';

interface Props {
  slug: string;
  initialText: string | null;
  initialProvider: string | null;
  initialGeneratedAt: string | null;
}

export function CommentaryBlock({
  slug, initialText, initialProvider, initialGeneratedAt,
}: Props) {
  const [text, setText] = useState<string | null>(initialText);
  const [provider, setProvider] = useState<string | null>(initialProvider);
  const [generatedAt, setGeneratedAt] = useState<string | null>(initialGeneratedAt);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const run = async (refresh: boolean) => {
    setError(null);
    setPending(true);
    try {
      const r = await apiClient<CommentaryResponse>(
        `/v1/investigations/${slug}/commentary${refresh ? '?refresh=true' : ''}`,
        { method: 'POST' },
      );
      setText(r.text);
      setProvider(r.provider);
      setGeneratedAt(r.generated_at);
    } catch (e) {
      setError(e instanceof ApiError ? e.message : 'Failed to generate commentary.');
    } finally {
      setPending(false);
    }
  };

  const isTemplate = provider === 'template' || (provider || '').startsWith('template');

  return (
    <Card>
      <div className="flex items-center justify-between gap-2 mb-2 flex-wrap">
        <CardLabel className="m-0 flex items-center gap-1.5">
          <Sparkles size={11} /> Analyst commentary
        </CardLabel>
        {provider && (
          <span
            className={`font-mono text-2xs tracking-wider uppercase ${
              isTemplate ? 'text-fg-mute' : 'text-accent'
            }`}
            title={`Generated by ${provider}`}
          >
            ▸ {isTemplate ? 'Template' : provider.replace(/^anthropic-/, '')}
          </span>
        )}
      </div>
      {!text ? (
        <>
          <CardTitle>No commentary yet</CardTitle>
          <p className="text-sm text-fg-dim mb-4 max-w-xl">
            Generate a brief, evidence-grounded analyst paragraph synthesizing this
            investigation's verdict and key findings. Uses Claude Haiku when an
            Anthropic API key is configured on the server; otherwise falls back
            to a deterministic template — both work, both ground the prose in
            the structured findings.
          </p>
          <Button onClick={() => run(false)} disabled={pending}>
            {pending ? <><Loader2 size={14} className="animate-spin" /> Generating…</> : <><Sparkles size={14} /> Generate commentary</>}
          </Button>
        </>
      ) : (
        <>
          <p className="text-sm text-fg leading-relaxed whitespace-pre-line">{text}</p>
          <div className="mt-4 flex items-center gap-3 flex-wrap">
            <Button variant="secondary" size="sm" onClick={() => run(true)} disabled={pending}>
              {pending ? <><Loader2 size={12} className="animate-spin" /> Regenerating…</> : <><RefreshCw size={12} /> Regenerate</>}
            </Button>
            {generatedAt && (
              <span className="font-mono text-2xs tracking-wider uppercase text-fg-mute">
                Generated {new Date(generatedAt).toLocaleString()}
              </span>
            )}
          </div>
        </>
      )}
      {error && (
        <p className="mt-3 text-xs text-danger bg-danger/10 border border-danger/40 rounded-sm px-3 py-2 font-mono">
          {error}
        </p>
      )}
    </Card>
  );
}
