"""Intelligence Library — seed knowledge entries (Sprint 025, Phase 2).

Practical, interlinked investigative expertise across every category. Each entry is real tradecraft
grounded in OmiSphere's evidence model (discriminative vs non-discriminative methods, the
corroboration gate, the precision frontier), carries its consuming specialists (the Phase-3
dependency source), and honors the constitution. GitHub is canonical; these are curated by
engineering and evolve only through reviewed revisions.
"""
from __future__ import annotations

from .entry import KnowledgeEntry, Revision

_R1 = (Revision("v1", "2026-07-01", "initial curated entry"),)
# constitutional-constraint shorthands (reference the constitution rules that bound each concept)
_C_GATE = "corroboration gate: non-discriminative or single-axis evidence cannot reach a coordinated verdict"
_C_EVID = "evidence, not verdict: cite bundle evidence; never assert a person IS a bot"
_C_SUPP = "supplemental signals carry zero suspicion weight"
_C_COUNTER = "counter-evidence mandatory: weigh the benign explanation"
_C_ECHO = "echo the engine number; never recompute or move the score"
_C_MEM = "memory/knowledge is background, never proof, never a citable evidence id"


def _e(**kw) -> KnowledgeEntry:
    kw.setdefault("revision_history", _R1)
    return KnowledgeEntry(**kw)


SEED_ENTRIES: tuple[KnowledgeEntry, ...] = (
    # ---- coordination techniques ---------------------------------------------------- #
    _e(id="coordinated_inauthentic_behavior", title="Coordinated Inauthentic Behavior (CIB)",
       category="coordination_techniques", confidence="established",
       definition="Multiple accounts acting together while misrepresenting their identity, "
                  "independence, or intent to manipulate perception.",
       purpose="The platform's central hostile concept — the thing coordination analysis exists to "
               "distinguish from legitimate, open coordination.",
       indicators=("discriminative coordination (fingerprint/co-engagement/co-tag) across accounts",
                   "concealed common control or funding", "manufactured appearance of independence"),
       counter_indicators=("open, disclosed coordination (an official group posting on-message)",
                           "high member authenticity + long independent histories"),
       evidence_requirements=("at least one discriminative, non-single-axis coordination method",
                              "corroboration across independent axes (behavior + network + timing)"),
       limitations=("coordination is not inherently hostile; inauthenticity is the added element",),
       false_positive_risks=("legitimate coordination (newsrooms, fandoms, campaigns) looks similar",),
       constitutional_constraints=(_C_GATE, _C_EVID, _C_COUNTER),
       relationships=("astroturfing", "engagement_pods", "sockpuppets", "discriminative_corroboration_gate",
                      "legitimate_coordination"),
       platforms=("youtube", "x", "reddit", "tiktok"),
       investigation_types=("campaign", "comment_section", "narrative"),
       tags=("cib", "coordination", "inauthentic", "manipulation"),
       specialists=("coordination_analyst", "campaign_analyst", "judge")),
    _e(id="engagement_pods", title="Engagement Pods", category="coordination_techniques",
       confidence="established",
       definition="Groups that agree to reciprocally like/comment/share each other's content to "
                  "game engagement-based ranking.",
       purpose="A common, often semi-legitimate coordination technique that must be read through the "
               "gate — reciprocal engagement alone is weakly discriminative.",
       indicators=("dense reciprocal co-engagement edges", "synchronized early engagement bursts",
                   "the same small set boosting each other across unrelated content"),
       counter_indicators=("a genuine tight-knit community that also engages organically",
                           "one-directional fan engagement (no reciprocity)"),
       evidence_requirements=("co_engagement clusters with reciprocity", "timing corroboration"),
       limitations=("pods span a spectrum from creator support groups to manipulation rings",),
       false_positive_risks=("gaming/fan communities co-engage heavily but authentically",),
       constitutional_constraints=(_C_GATE, _C_COUNTER),
       relationships=("co_engagement_coordination", "coordinated_inauthentic_behavior", "organic_virality"),
       platforms=("x", "tiktok", "youtube"), investigation_types=("comment_section", "campaign"),
       tags=("pods", "engagement", "reciprocal", "co_engagement"),
       specialists=("network_analyst", "coordination_analyst", "temporal_analyst")),
    _e(id="fingerprint_clustering", title="Fingerprint Clustering", category="coordination_techniques",
       confidence="established",
       definition="Grouping accounts by shared device/behavioral fingerprints that are hard to fake "
                  "and rarely coincide by chance.",
       purpose="A DISCRIMINATIVE method — strong enough to corroborate a coordinated read on its own "
               "axis (unlike style or timing).",
       indicators=("shared rare fingerprints across nominally independent accounts",
                   "clusters that persist across sessions"),
       counter_indicators=("shared infrastructure with an innocent explanation (household, office, VPN)",),
       evidence_requirements=("a fingerprint_cluster method firing with named members",),
       limitations=("shared environment is not shared control; corroborate intent",),
       false_positive_risks=("families, offices, and NAT/VPN pools share fingerprints legitimately",),
       constitutional_constraints=(_C_GATE, _C_EVID),
       relationships=("discriminative_corroboration_gate", "coordinated_inauthentic_behavior"),
       platforms=("youtube", "x"), investigation_types=("comment_section", "campaign"),
       tags=("fingerprint", "device", "discriminative", "cluster"),
       specialists=("coordination_analyst", "network_analyst")),
    _e(id="co_engagement_coordination", title="Co-engagement Coordination",
       category="coordination_techniques", confidence="established",
       definition="Accounts repeatedly engaging the same targets in the same windows, revealing a "
                  "shared coordination signal.",
       purpose="A discriminative coordination axis when the overlap is improbable by chance.",
       indicators=("improbably high shared-target overlap", "repeated across multiple targets/windows"),
       counter_indicators=("a popular target everyone independently engages",
                           "topical communities with naturally overlapping interests"),
       evidence_requirements=("co_engagement method with quantified overlap above chance",),
       limitations=("popularity inflates overlap; normalize against base engagement",),
       false_positive_risks=("mega-popular content produces organic co-engagement",),
       constitutional_constraints=(_C_GATE, _C_COUNTER),
       relationships=("engagement_pods", "discriminative_corroboration_gate", "organic_virality"),
       platforms=("x", "youtube", "tiktok"), investigation_types=("comment_section", "campaign"),
       tags=("co_engagement", "overlap", "discriminative"),
       specialists=("network_analyst", "coordination_analyst")),
    # ---- behavioral archetypes ------------------------------------------------------ #
    _e(id="sockpuppets", title="Sockpuppets", category="behavioral_archetypes", confidence="established",
       definition="Multiple personas operated by one actor to fake independent voices.",
       purpose="A core deception archetype; distinguishes one-actor-many-masks from many real people.",
       indicators=("fingerprint/style matches across 'independent' personas",
                   "staggered timing that avoids simultaneous presence", "shared idiosyncratic errors"),
       counter_indicators=("genuinely distinct writing, histories, and social graphs",),
       evidence_requirements=("a discriminative match (fingerprint or strong stylometric) across personas",),
       limitations=("stylometry alone is weak; require a discriminative corroborator",),
       false_positive_risks=("shared templates or a house style can mimic one author",),
       constitutional_constraints=(_C_GATE, _C_EVID, _C_MEM),
       relationships=("stylometric_matching", "coordinated_inauthentic_behavior", "fingerprint_clustering"),
       platforms=("reddit", "x", "youtube"), investigation_types=("comment_section", "account"),
       tags=("sockpuppet", "persona", "one-actor"),
       specialists=("behavior_analyst", "language_analyst", "network_analyst")),
    _e(id="temporal_synchrony", title="Temporal Synchrony", category="behavioral_archetypes",
       confidence="established",
       definition="Tight time-clustering of actions across accounts, suggesting a shared trigger or "
                  "scheduler.",
       purpose="A frequently over-read signal: synchrony is NON-discriminative on its own.",
       indicators=("bursts far tighter than organic reaction", "regular mechanical inter-post intervals"),
       counter_indicators=("a real-world event that triggers organic simultaneous posting",
                           "timezone-clustered but independent audiences"),
       evidence_requirements=("burst_synchrony plus a discriminative corroborator for a hostile read",),
       limitations=("timing alone cannot drive a coordinated verdict (single-axis)",),
       false_positive_risks=("breaking news causes organic synchrony; schedulers are often benign",),
       constitutional_constraints=(_C_GATE, _C_COUNTER),
       relationships=("single_axis_cap", "bot_amplification", "organic_virality", "benign_automation"),
       platforms=("x", "youtube", "tiktok"), investigation_types=("narrative", "comment_section"),
       tags=("temporal", "synchrony", "burst", "non-discriminative"),
       specialists=("temporal_analyst", "coordination_analyst")),
    _e(id="new_account_cohorts", title="New-account Cohorts", category="behavioral_archetypes",
       confidence="emerging",
       definition="Clusters of accounts created in the same narrow window, sometimes preceding a push.",
       purpose="A weak, corroborating metadata signal — never decisive alone.",
       indicators=("synchronized creation timestamps", "sparse history then sudden coordinated activity"),
       counter_indicators=("a platform growth event or campaign onboarding real new users",),
       evidence_requirements=("age_cohort clustering plus a discriminative corroborator",),
       limitations=("age_cohort is non-discriminative; new != inauthentic",),
       false_positive_risks=("viral moments and ad campaigns create legitimate new-user waves",),
       constitutional_constraints=(_C_GATE, "no ageism: a new account is not inauthentic by itself"),
       relationships=("temporal_synchrony", "discriminative_corroboration_gate"),
       platforms=("x", "youtube"), investigation_types=("campaign", "comment_section"),
       tags=("age_cohort", "new_accounts", "creation_burst", "metadata"),
       specialists=("metadata_analyst",)),
    # ---- bot behaviors -------------------------------------------------------------- #
    _e(id="bot_amplification", title="Bot Amplification", category="bot_behaviors", confidence="established",
       definition="Automated accounts inflating reach/engagement of target content.",
       purpose="A canonical hostile automation pattern — but must be separated from benign automation.",
       indicators=("mechanical cadence, minimal original content, high amplification ratio",
                   "fingerprint/co-engagement links across the bot set"),
       counter_indicators=("disclosed bots (news tickers), verified automation, human-like variability"),
       evidence_requirements=("discriminative coordination across the automated set + behavior signals",),
       limitations=("automation is a means, not proof of inauthentic intent",),
       false_positive_risks=("legitimate schedulers and assistive tooling look automated",),
       constitutional_constraints=(_C_GATE, _C_EVID, _C_COUNTER),
       relationships=("benign_automation", "temporal_synchrony", "manufactured_amplification"),
       platforms=("x", "youtube", "tiktok"), investigation_types=("narrative", "campaign"),
       tags=("bot", "automation", "amplification"),
       specialists=("behavior_analyst", "temporal_analyst", "network_analyst")),
    _e(id="benign_automation", title="Benign Automation", category="bot_behaviors", confidence="established",
       definition="Legitimate scheduled/automated posting (news feeds, cross-posters, disclosed bots).",
       purpose="The precision-frontier twin of bot amplification — protects legitimate automation.",
       indicators=("disclosed automation, consistent legitimate purpose, stable long history",),
       counter_indicators=("concealment of automation combined with a manipulation target",),
       evidence_requirements=("evidence of disclosure/legitimacy; absence of discriminative coordination",),
       limitations=("benign and hostile automation share surface signals; intent needs corroboration",),
       false_positive_risks=("flagging a scheduler or newsroom feed as a botnet",),
       constitutional_constraints=(_C_COUNTER, _C_EVID),
       relationships=("bot_amplification", "precision_frontier", "legitimate_coordination"),
       platforms=("x", "youtube"), investigation_types=("account", "campaign"),
       tags=("automation", "scheduler", "benign", "false_positive"),
       specialists=("counter_evidence_analyst", "behavior_analyst", "risk_analyst")),
    # ---- legitimate community patterns + false positives + organic --------------------- #
    _e(id="legitimate_coordination", title="Legitimate Coordination",
       category="legitimate_community_patterns", confidence="established",
       definition="Open, authentic coordination — newsrooms on-message, fan communities, official "
                  "campaigns, benign scheduling.",
       purpose="The precision frontier's positive model: coordination that must NEVER read as hostile.",
       indicators=("disclosed/known group identity, high member authenticity, long independent histories",),
       counter_indicators=("concealed control, fabricated independence, discriminative deception signals"),
       evidence_requirements=("member authenticity/history; a legitimate-coordination prior in memory"),
       limitations=("legitimacy raises the bar for a hostile read but does not preclude investigation",),
       false_positive_risks=("this IS the false-positive class — err toward not flagging it",),
       constitutional_constraints=(_C_COUNTER, _C_MEM, _C_GATE),
       relationships=("precision_frontier", "coordinated_inauthentic_behavior", "benign_automation",
                      "organic_virality"),
       platforms=("youtube", "x", "reddit"), investigation_types=("campaign", "narrative"),
       tags=("legitimate", "newsroom", "fandom", "precision_frontier"),
       specialists=("counter_evidence_analyst", "campaign_analyst", "risk_analyst")),
    _e(id="precision_frontier", title="The Precision Frontier", category="false_positive_patterns",
       confidence="established",
       definition="The discipline that legitimate coordination and benign automation must not be "
                  "read as hostile — false positives here are the most costly error.",
       purpose="Encodes OmiSphere's core trust principle as reusable knowledge.",
       indicators=("a hostile pattern present but with a strong benign explanation unrebutted",),
       counter_indicators=("discriminative, corroborated deception that the benign story cannot explain",),
       evidence_requirements=("explicit weighing of the benign hypothesis before any hostile label",),
       limitations=("protecting precision can cost recall; state the trade-off, don't hide it",),
       false_positive_risks=("the whole entry is about preventing them",),
       constitutional_constraints=(_C_COUNTER, _C_GATE, "controls must show zero-FPR before promotion"),
       relationships=("legitimate_coordination", "organic_virality", "second_language_writing",
                      "benign_automation"),
       platforms=("youtube", "x", "reddit", "tiktok"),
       investigation_types=("campaign", "narrative", "comment_section"),
       tags=("false_positive", "precision", "legitimacy"),
       specialists=("counter_evidence_analyst", "risk_analyst", "judge")),
    _e(id="second_language_writing", title="Second-language & Templated Writing",
       category="false_positive_patterns", confidence="emerging",
       definition="Non-native phrasing, shared templates, or a house style that superficially mimics "
                  "coordinated/scripted text.",
       purpose="A common stylometric false positive that language analysis must guard against.",
       indicators=("repeated non-idiomatic constructions across posters",),
       counter_indicators=("a shared first language or community register explains the overlap",),
       evidence_requirements=("distinguish rare engineered verbatim templates from common phrasing",),
       limitations=("style is non-discriminative; never drives a coordinated verdict alone",),
       false_positive_risks=("penalizing ESL communities or house styles as bot networks",),
       constitutional_constraints=(_C_GATE, _C_SUPP),
       relationships=("stylometric_matching", "precision_frontier"),
       platforms=("youtube", "reddit", "x"), investigation_types=("comment_section",),
       tags=("stylometry", "esl", "template", "false_positive"),
       specialists=("language_analyst", "counter_evidence_analyst")),
    _e(id="organic_virality", title="Organic Viral Signatures", category="organic_viral_signatures",
       confidence="established",
       definition="What genuine virality looks like: broad, diverse, independent participation with "
                  "heavy-tailed reach.",
       purpose="A positive authenticity model to weigh against manufactured amplification.",
       indicators=("high distinct-author breadth, diverse histories, uncoordinated timing",
                   "organic reaction spread following influential nodes"),
       counter_indicators=("narrow authorship, templated text, synchronized discriminative coordination",),
       evidence_requirements=("author-breadth and diversity metrics; absence of discriminative coordination",),
       limitations=("virality can be seeded then organic; grain and window matter",),
       false_positive_risks=("reading popularity itself as inauthenticity",),
       constitutional_constraints=(_C_COUNTER, _C_ECHO),
       relationships=("manufactured_amplification", "precision_frontier", "legitimate_coordination"),
       platforms=("tiktok", "x", "youtube"), investigation_types=("narrative", "comment_section"),
       tags=("organic", "viral", "breadth", "authentic"),
       specialists=("narrative_analyst", "counter_evidence_analyst")),
    # ---- narrative amplification + influence operations ------------------------------- #
    _e(id="manufactured_amplification", title="Manufactured Amplification",
       category="narrative_amplification", confidence="established",
       definition="Coordinated inflation of a message's apparent reach/consensus, as opposed to "
                  "organic spread.",
       purpose="Separates narrative-grain amplification from genuine diffusion.",
       indicators=("narrow templated authorship, synchronized pushes, low distinct-author breadth",),
       counter_indicators=("broad diverse authorship; organic reaction curves",),
       evidence_requirements=("narrative inauthenticity_score + coordination corroboration",),
       limitations=("message-cluster grain differs from account-campaign grain — don't conflate",),
       false_positive_risks=("a genuinely popular message with some amplification is still mostly organic",),
       constitutional_constraints=(_C_GATE, _C_COUNTER),
       relationships=("organic_virality", "astroturfing", "consensus_illusion", "bot_amplification"),
       platforms=("x", "tiktok", "youtube"), investigation_types=("narrative",),
       tags=("amplification", "narrative", "manufactured"),
       specialists=("narrative_analyst", "language_analyst")),
    _e(id="astroturfing", title="Astroturfing", category="influence_operations", confidence="established",
       definition="Manufacturing the appearance of grassroots support to disguise an organized or "
                  "funded campaign.",
       purpose="A flagship influence technique linking coordination, narrative, and deception.",
       indicators=("fabricated independence, templated 'personal' testimony, coordinated timing",),
       counter_indicators=("genuine grassroots breadth with authentic, independent participants",),
       evidence_requirements=("discriminative coordination + narrative templating + authenticity gaps",),
       limitations=("real grassroots movements also coordinate; the deception is the differentiator",),
       false_positive_risks=("legitimate activism and fan mobilization mistaken for astroturf",),
       constitutional_constraints=(_C_GATE, _C_EVID, _C_COUNTER),
       relationships=("manufactured_amplification", "consensus_illusion", "sockpuppets",
                      "legitimate_coordination"),
       platforms=("x", "reddit", "youtube"), investigation_types=("campaign", "narrative"),
       tags=("astroturf", "grassroots", "influence"),
       specialists=("narrative_analyst", "coordination_analyst", "counter_evidence_analyst")),
    _e(id="consensus_illusion", title="Consensus Illusion", category="influence_operations",
       confidence="emerging",
       definition="Creating a false impression that a view is widely held, to trigger social proof "
                  "and bandwagon effects.",
       purpose="Names the intended cognitive effect behind much manufactured amplification.",
       indicators=("a loud coordinated minority presented as majority, repetition across shells",),
       counter_indicators=("genuinely broad, independent agreement",),
       evidence_requirements=("amplification + coordination evidence; effect stated as hypothesis"),
       limitations=("intended effect is inferred, never proven; describe, don't mind-read",),
       false_positive_risks=("a genuinely popular consensus read as manufactured",),
       constitutional_constraints=(_C_EVID, "effects are hypotheses, never proven intent"),
       relationships=("manufactured_amplification", "astroturfing"),
       platforms=("x", "reddit"), investigation_types=("narrative",),
       tags=("consensus", "social_proof", "bandwagon", "psychological"),
       specialists=("narrative_analyst", "judge")),
    _e(id="coordinated_campaign", title="Coordinated Campaign", category="campaign_types",
       confidence="established",
       definition="A materialized cluster of accounts acting together over time toward a shared goal "
                  "— which may be hostile OR legitimate.",
       purpose="Frames the campaign grain and forces the legitimate-vs-hostile determination.",
       indicators=("persistent membership, shared methods, coordinated observations over time",),
       counter_indicators=("high mean member authenticity, disclosed legitimate purpose",),
       evidence_requirements=("member authenticity + discriminative coordination + observation history",),
       limitations=("a campaign label is a description of structure, not a verdict of intent",),
       false_positive_risks=("official/fan campaigns are legitimate coordinated campaigns",),
       constitutional_constraints=(_C_COUNTER, _C_GATE, _C_MEM),
       relationships=("coordinated_inauthentic_behavior", "legitimate_coordination", "astroturfing"),
       platforms=("x", "youtube"), investigation_types=("campaign",),
       tags=("campaign", "materialized", "membership"),
       specialists=("campaign_analyst", "coordination_analyst")),
    # ---- deception indicators ------------------------------------------------------- #
    _e(id="stylometric_matching", title="Stylometric Matching", category="deception_indicators",
       confidence="emerging",
       definition="Similarity of writing style across accounts, suggesting shared authorship or "
                  "templates.",
       purpose="A NON-discriminative deception indicator — corroborating, never decisive.",
       indicators=("rare verbatim templates repeated across many independent accounts",),
       counter_indicators=("common phrasing, shared register, ESL patterns, a single pair only",),
       evidence_requirements=("style_match plus a discriminative corroborator for any hostile read",),
       limitations=("style_match alone cannot drive a coordinated verdict",),
       false_positive_risks=("house styles, memes, and second-language writing (see that entry)",),
       constitutional_constraints=(_C_GATE, _C_SUPP),
       relationships=("second_language_writing", "sockpuppets", "discriminative_corroboration_gate"),
       platforms=("reddit", "youtube", "x"), investigation_types=("comment_section",),
       tags=("stylometry", "style_match", "non-discriminative"),
       specialists=("language_analyst",)),
    # ---- platform behaviors --------------------------------------------------------- #
    _e(id="platform_youtube_norms", title="YouTube Platform Norms", category="platform_behaviors",
       confidence="emerging",
       definition="YouTube-specific behaviors and signal meanings (comment sections, reply pods, "
                  "sub-driven engagement).",
       purpose="Prevents mis-reading YouTube signals with another platform's assumptions.",
       indicators=("comment-section reply pods, coordinated early comments on new uploads",),
       counter_indicators=("large fan bases produce dense but authentic comment engagement",),
       evidence_requirements=("scope any norm to YouTube + the capture window",),
       limitations=("norms drift; date every platform claim",),
       false_positive_risks=("applying X/Twitter thresholds to YouTube engagement",),
       constitutional_constraints=(_C_EVID,),
       relationships=("engagement_pods", "platform_x_norms"),
       platforms=("youtube",), investigation_types=("comment_section",),
       tags=("youtube", "platform", "comments"),
       specialists=("metadata_analyst", "behavior_analyst")),
    _e(id="platform_x_norms", title="X / Twitter Platform Norms", category="platform_behaviors",
       confidence="emerging",
       definition="X-specific behaviors (retweet cascades, reply-guy dynamics, quote-tweet ratios).",
       purpose="Grounds coordination reads in X's engagement mechanics.",
       indicators=("retweet cascades from a coordinated seed set, ratioed reply swarms",),
       counter_indicators=("organic cascades following genuinely influential accounts",),
       evidence_requirements=("normalize against X base rates; scope to capture window",),
       limitations=("X mechanics change frequently; date the norm",),
       false_positive_risks=("treating a viral cascade as coordinated amplification",),
       constitutional_constraints=(_C_EVID,),
       relationships=("manufactured_amplification", "platform_youtube_norms"),
       platforms=("x",), investigation_types=("narrative",),
       tags=("x", "twitter", "platform", "retweet"),
       specialists=("metadata_analyst", "behavior_analyst")),
    # ---- heuristics + OSINT + calibration ------------------------------------------- #
    _e(id="discriminative_corroboration_gate", title="Discriminative Corroboration Gate",
       category="investigative_heuristics", confidence="established",
       definition="The rule that only discriminative, non-single-axis, corroborated evidence may "
                  "reach a maximal coordinated verdict.",
       purpose="OmiSphere's central precision heuristic, encoded as reusable knowledge.",
       indicators=("two independent discriminative axes converging",),
       counter_indicators=("a single non-discriminative detector carrying the read (single-axis)",),
       evidence_requirements=("classify each method discriminative vs not; require corroboration"),
       limitations=("the gate trades some recall for precision by design",),
       false_positive_risks=("bypassing the gate is the primary source of hostile false positives",),
       constitutional_constraints=(_C_GATE, "the Governor enforces this in code"),
       relationships=("fingerprint_clustering", "co_engagement_coordination", "single_axis_cap",
                      "temporal_synchrony", "stylometric_matching"),
       platforms=("youtube", "x", "reddit", "tiktok"),
       investigation_types=("comment_section", "campaign", "narrative"),
       tags=("corroboration", "discriminative", "gate", "heuristic"),
       specialists=("coordination_analyst", "calibration_analyst", "judge")),
    _e(id="base_rate_discipline", title="Base-rate Discipline", category="investigative_heuristics",
       confidence="established",
       definition="Interpreting overlap/synchrony/co-presence relative to how common they are under "
                  "innocent conditions.",
       purpose="Prevents mistaking popularity-driven coincidence for coordination.",
       indicators=("overlap far exceeding the base rate for comparable popular content",),
       counter_indicators=("overlap explained by target popularity or topical community size",),
       evidence_requirements=("a base-rate comparison, not a raw overlap count",),
       limitations=("good base rates are hard; state the assumption",),
       false_positive_risks=("raw co-occurrence on popular targets reads as coordination",),
       constitutional_constraints=(_C_COUNTER, _C_ECHO),
       relationships=("co_engagement_coordination", "organic_virality", "confidence_bands"),
       platforms=("x", "youtube", "tiktok"), investigation_types=("comment_section", "narrative"),
       tags=("base_rate", "heuristic", "coincidence"),
       specialists=("calibration_analyst", "risk_analyst")),
    _e(id="independent_corroboration", title="Independent Corroboration", category="osint_techniques",
       confidence="established",
       definition="Requiring evidence from independent axes/sources before raising confidence — "
                  "avoiding double-counting one observation.",
       purpose="Core OSINT tradecraft mirrored by the memory system's independence rule.",
       indicators=("agreement across behavior, network, timing, and metadata that are truly independent",),
       counter_indicators=("multiple 'signals' that are restatements of one underlying observation",),
       evidence_requirements=("distinct independence keys; no primed self-confirmation",),
       limitations=("apparent independence can hide a common cause",),
       false_positive_risks=("double-counting inflates confidence on thin evidence",),
       constitutional_constraints=(_C_EVID, _C_MEM),
       relationships=("discriminative_corroboration_gate", "single_axis_cap"),
       platforms=("youtube", "x", "reddit"), investigation_types=("campaign", "comment_section"),
       tags=("corroboration", "independence", "osint"),
       specialists=("counter_evidence_analyst", "judge", "memory_analyst")),
    _e(id="single_axis_cap", title="Single-axis Cap", category="confidence_calibration",
       confidence="established",
       definition="When one detector carries the score with no independent corroboration, the verdict "
                  "and confidence are capped.",
       purpose="Prevents one signal from producing a maximal, over-confident read.",
       indicators=("single_axis_capped flag set on the bundle",),
       counter_indicators=("multiple independent discriminative axes present",),
       evidence_requirements=("check the corroboration facet before assigning a high band",),
       limitations=("a capped read can still be correct — cap confidence, not curiosity",),
       false_positive_risks=("ignoring the cap yields inflated coordinated verdicts",),
       constitutional_constraints=(_C_GATE, "single-axis or non-discriminative caps at 'moderate'"),
       relationships=("discriminative_corroboration_gate", "confidence_bands", "temporal_synchrony"),
       platforms=("youtube", "x"), investigation_types=("comment_section", "campaign", "narrative"),
       tags=("single_axis", "cap", "calibration"),
       specialists=("calibration_analyst", "judge")),
    _e(id="confidence_bands", title="Confidence Bands", category="confidence_calibration",
       confidence="established",
       definition="Mapping evidence strength + quantity to a calibrated band (insufficient / low / "
                  "moderate / high), independent of accusation severity.",
       purpose="Keeps confidence honest — thin data means low confidence even for alarming patterns.",
       indicators=("high band only with >=1 discriminative, non-single-axis method and adequate data",),
       counter_indicators=("thin data, abstained detectors, single-axis evidence",),
       evidence_requirements=("corroboration state + data quantity, not the severity of the claim",),
       limitations=("bands are guidance; the Governor enforces the hard caps",),
       false_positive_risks=("severity-driven over-confidence on thin evidence",),
       constitutional_constraints=(_C_ECHO, "confidence reflects evidence, not accusation severity"),
       relationships=("single_axis_cap", "base_rate_discipline", "independent_corroboration"),
       platforms=("youtube", "x", "reddit", "tiktok"),
       investigation_types=("comment_section", "campaign", "narrative"),
       tags=("confidence", "calibration", "bands"),
       specialists=("calibration_analyst", "judge")),
)

__all__ = ["SEED_ENTRIES"]
