-- Supabase memory store — Institutional Intelligence Memory (Sprint 012).
--
-- APPLIED to the dedicated Supabase memory project (OMI_MEMORY_DATABASE_URL) on 2026-06-26
-- via the Supabase connector (migration name: 0008_memory_tables). This file is the source of
-- truth for what is in Supabase and mirrors the portable schema in
-- app/storage/models.py + alembic/versions/0008_memory_tables.py.
--
-- Why a separate file: the Alembic migration is portable (it also runs on the SQLite test DB
-- and the main app DB) and therefore cannot carry Postgres/Supabase-only hardening. The DDL
-- below is identical in structure to Alembic 0008, PLUS Row Level Security: institutional
-- memory is BACKEND-ONLY. Enabling RLS with no policies denies the anon/authenticated PostgREST
-- roles; the backend connects as the postgres owner role and is unaffected. Memory must never
-- be exposed via the public API.
--
-- Constitutional note: confidence, contradiction history, and epistemic status are NEVER stored
-- — they are recomputed from the append-only observation_ledger by the domain model.
-- Idempotent: safe to re-apply.

CREATE TABLE IF NOT EXISTS public.knowledge_objects (
    id               text PRIMARY KEY,
    type             text NOT NULL,
    family           text NOT NULL DEFAULT 'patterns_signatures',
    label            text NOT NULL DEFAULT '',
    signature        jsonb,
    attributes       jsonb,
    is_control       boolean NOT NULL DEFAULT false,
    influence_class  text NOT NULL DEFAULT 'context',
    superseded_by    text,
    half_life_days   double precision NOT NULL DEFAULT 180.0,
    retirement_floor double precision NOT NULL DEFAULT 0.12,
    platform_scope   jsonb,
    created_at       timestamptz
);
CREATE INDEX IF NOT EXISTS ix_knowledge_objects_type ON public.knowledge_objects (type);
CREATE INDEX IF NOT EXISTS ix_knowledge_objects_is_control ON public.knowledge_objects (is_control);
CREATE INDEX IF NOT EXISTS ix_ko_type_control ON public.knowledge_objects (type, is_control);
CREATE INDEX IF NOT EXISTS ix_ko_active ON public.knowledge_objects (superseded_by);

CREATE TABLE IF NOT EXISTS public.knowledge_object_signatures (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ko_id  text NOT NULL REFERENCES public.knowledge_objects(id) ON DELETE CASCADE,
    token  text NOT NULL,
    CONSTRAINT uq_kosig_ko_token UNIQUE (ko_id, token)
);
CREATE INDEX IF NOT EXISTS ix_knowledge_object_signatures_ko_id ON public.knowledge_object_signatures (ko_id);
CREATE INDEX IF NOT EXISTS ix_kosig_token ON public.knowledge_object_signatures (token);

CREATE TABLE IF NOT EXISTS public.observation_ledger (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ko_id            text NOT NULL REFERENCES public.knowledge_objects(id) ON DELETE CASCADE,
    seq              integer NOT NULL DEFAULT 0,
    investigation    text NOT NULL,
    stance           text NOT NULL,
    evidence_refs    jsonb,
    independence_key text NOT NULL DEFAULT '',
    at               text NOT NULL DEFAULT '',
    human_anchor     jsonb,
    memory_influence text NOT NULL DEFAULT 'none',
    created_at       timestamptz
);
CREATE INDEX IF NOT EXISTS ix_observation_ledger_ko_id ON public.observation_ledger (ko_id);
CREATE INDEX IF NOT EXISTS ix_observation_ledger_investigation ON public.observation_ledger (investigation);
CREATE INDEX IF NOT EXISTS ix_obs_ko_seq ON public.observation_ledger (ko_id, seq);
CREATE INDEX IF NOT EXISTS ix_obs_stance ON public.observation_ledger (stance);

CREATE TABLE IF NOT EXISTS public.memory_revisions (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ko_id         text NOT NULL REFERENCES public.knowledge_objects(id) ON DELETE CASCADE,
    rev           integer NOT NULL DEFAULT 1,
    change        text NOT NULL DEFAULT '',
    investigation text,
    at            text,
    created_at    timestamptz
);
CREATE INDEX IF NOT EXISTS ix_memory_revisions_ko_id ON public.memory_revisions (ko_id);
CREATE INDEX IF NOT EXISTS ix_memrev_ko ON public.memory_revisions (ko_id, rev);

CREATE TABLE IF NOT EXISTS public.prior_context_cache (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signature_hash  text NOT NULL UNIQUE,
    result          jsonb,
    memory_revision text,
    computed_at     timestamptz
);
CREATE INDEX IF NOT EXISTS ix_pcc_sig ON public.prior_context_cache (signature_hash);

-- Row Level Security: backend-only. No policies => anon/authenticated are denied; the postgres
-- owner role (the backend connection) bypasses RLS. Do NOT add permissive policies — that would
-- expose institutional memory to the public API.
ALTER TABLE public.knowledge_objects            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_object_signatures  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observation_ledger           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_revisions             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prior_context_cache          ENABLE ROW LEVEL SECURITY;
