-- Supabase memory store — retrieval feedback + reuse counter (Sprint 014).
--
-- Mirrors alembic/versions/0010_retrieval_feedback.py. Adds the append-only `retrieval_feedback`
-- table (records WHY a memory was retrieved and what happened — influenced / governor-accepted /
-- analyst-agreed) and a denormalized `reuse_count` on knowledge_objects. Both are MEASUREMENTS
-- that improve future retrieval RANKING only; they never change an investigation's score, the
-- Governor, or OmiScore. Idempotent.
-- Applied to the dedicated Supabase memory project on 2026-06-30 (migration 0010_retrieval_feedback).

ALTER TABLE public.knowledge_objects
    ADD COLUMN IF NOT EXISTS reuse_count integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.retrieval_feedback (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ko_id             text NOT NULL REFERENCES public.knowledge_objects(id) ON DELETE CASCADE,
    investigation     text NOT NULL,
    selected_because  text NOT NULL DEFAULT '',
    influenced        boolean NOT NULL DEFAULT false,
    governor_accepted boolean NOT NULL DEFAULT false,
    analyst_agreed    boolean NOT NULL DEFAULT false,
    at                text NOT NULL DEFAULT '',
    created_at        timestamptz
);
CREATE INDEX IF NOT EXISTS ix_retrieval_feedback_ko_id ON public.retrieval_feedback (ko_id);
CREATE INDEX IF NOT EXISTS ix_retrieval_feedback_investigation ON public.retrieval_feedback (investigation);
CREATE INDEX IF NOT EXISTS ix_rfb_ko ON public.retrieval_feedback (ko_id);

-- Row Level Security: backend-only, identical to the other memory tables. No policies =>
-- anon/authenticated (PostgREST) are denied; the postgres owner role (the backend connection)
-- bypasses RLS. Do NOT add permissive policies — that would expose institutional learning to the
-- public API.
ALTER TABLE public.retrieval_feedback ENABLE ROW LEVEL SECURITY;
