"""Report templates.

`build_report_view()` returns a structured dict shaped for the Next.js
public renderer. `render_markdown()` produces a plain-text Markdown
export.

Both consume the same persisted investigation payload, so what the
recipient sees on the web matches what they get when they download.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

Template = Literal["executive", "evidence"]


# ---------------------------------------------------------------------------
# View builder (consumed by the Next.js public page)
# ---------------------------------------------------------------------------


def build_report_view(
    *,
    template: Template,
    investigation: dict,
    payload: dict,
) -> dict:
    """Return a JSON-serializable view model for the public report page.

    The investigation dict has slug/label/input_url/etc. The payload is
    the full ComprehensiveScanResult that was stored at scan time.
    """
    flagged = _flagged_commenters(payload)
    everyone = _all_commenters(payload)
    commentary = None
    if investigation.get("commentary_text"):
        commentary = {
            "text": investigation["commentary_text"],
            "provider": investigation.get("commentary_provider") or "template",
            "generated_at": _iso(investigation.get("commentary_generated_at")),
        }
    return {
        "meta": {
            "template": template,
            "slug": investigation["slug"],
            "label": investigation["label"],
            "input_url": investigation["input_url"],
            "kind": investigation["kind"],
            "created_at": _iso(investigation.get("created_at")),
            "published_at": _iso(investigation.get("published_at")),
            "batch_count": investigation.get("batch_count", 1),
            "quota_used": investigation.get("quota_used", 0),
            # Funnel facts. Both are real or absent, never estimated: `commenters_available` is the
            # compiled total for the post (NULL on rows written before it was recorded) and
            # `read_count` is the deduped public-view count for this token. The page shows each only
            # when it has one, because a made-up number on a report about fake engagement is the one
            # lie that would discredit everything else on the page.
            "commenters_scanned": _scanned_count(payload),
            "commenters_available": investigation.get("commenters_available"),
            "read_count": investigation.get("read_count"),
        },
        "commentary": commentary,
        "verdict": {
            "overall_probability": payload.get("overall_probability", 0.0),
            "overall_tier": payload.get("overall_tier", "low"),
            "summary": payload.get("summary", ""),
            "convergence_score": payload.get("convergence_score", 0.0),
        },
        "inputs_provided": payload.get("inputs_provided", []),
        "headline_cross_link": _headline_cross_link(payload),
        "cross_links": (
            payload.get("cross_links", []) if template == "evidence"
            else _top_cross_links(payload, n=3)
        ),
        "focus_account": _summarize_focus_account(payload.get("focus_account")),
        "top_flagged": flagged[: 10 if template == "evidence" else 5],
        "total_flagged": len(flagged),
        # Every account scored, worst first. The report leads with this now: a list of only the
        # flagged ones reads as an accusation, while the full list reads as analysis and makes the
        # clean majority visible.
        "all_commenters": everyone,
        "total_scanned": _scanned_count(payload),
        "video": _summarize_video(payload.get("video"), template),
        "methodology": _methodology_note(),
        "stats": _stats_block(
            payload, commenters_available=investigation.get("commenters_available"),
        ),
    }


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------


def render_markdown(
    *,
    template: Template,
    investigation: dict,
    payload: dict,
) -> str:
    v = build_report_view(template=template, investigation=investigation, payload=payload)
    lines: list[str] = []

    add = lines.append
    meta = v["meta"]
    verdict = v["verdict"]
    pct = int(round(verdict["overall_probability"] * 100))
    tier_label = (verdict["overall_tier"] or "low").upper()

    add(f"# OMISPHERE Report — {meta['label']}")
    add("")
    add("_Generated by OMISPHERE · Probabilistic Authenticity Intelligence_")
    add("")
    add(f"- **Slug:** `{meta['slug']}`")
    add(f"- **Input:** `{meta['input_url']}`")
    add(f"- **Kind:** {meta['kind']}")
    add(f"- **Scanned:** {meta['created_at'] or '—'}")
    add(f"- **Batches:** {meta['batch_count']}  ·  **YT quota:** {meta['quota_used']} units")
    add("")
    add("---")
    add("")
    add("## Verdict")
    add("")
    add(f"**{pct}% — {tier_label} suspicion**")
    add("")
    add(verdict["summary"] or "(no summary)")
    add("")

    if v.get("commentary"):
        c = v["commentary"]
        add("## Analyst commentary")
        add("")
        add(c["text"])
        add("")
        add(f"_Generated by {c['provider']}._")
        add("")

    if v["headline_cross_link"]:
        h = v["headline_cross_link"]
        add("## The finding")
        add("")
        add(f"**{(h.get('kind') or '').replace('_',' ').upper()}** · severity `{h.get('severity')}`")
        add("")
        add(h.get("summary", ""))
        for ev in h.get("evidence", [])[:3]:
            add(f"> {ev}")
        add("")

    if v["focus_account"]:
        fa = v["focus_account"]
        add("## Focus account")
        add("")
        add(f"- **Handle:** {fa['handle']}")
        add(f"- **Tier:** {fa['tier']}")
        add(f"- **Probability:** {int(round(fa['overall_probability']*100))}%")
        if fa.get("intent_label"):
            add(f"- **Suspected intent:** {fa['intent_label']}")
        if fa.get("summary"):
            add("")
            add(fa["summary"])
        if fa.get("reasons"):
            add("")
            add("**Why flagged:**")
            for r in fa["reasons"][:6]:
                add(f"- {r}")
        add("")

    # Every account scored, worst first. The export has to match what the page shows, or someone who
    # downloads the report as evidence has a different document from the one they read.
    if v["all_commenters"]:
        add(f"## Accounts scanned · {v['total_scanned']} total, {v['total_flagged']} flagged")
        add("")
        add("| Handle | Tier | Probability | Intent |")
        add("|---|---|---|---|")
        for c in v["all_commenters"]:
            add(
                f"| {c['handle']} | {c['tier']} | "
                f"{int(round(c['overall_probability']*100))}% | "
                f"{c.get('intent_label') or '-'} |"
            )
        add("")

    if template == "evidence" and v["cross_links"]:
        add(f"## Cross-links · {len(v['cross_links'])}")
        add("")
        for cl in v["cross_links"]:
            add(f"### {(cl.get('kind') or '').replace('_',' ').upper()}  ·  `{cl.get('severity')}`")
            add("")
            add(cl.get("summary", ""))
            for ev in cl.get("evidence", [])[:5]:
                add(f"> {ev}")
            add("")

    stats = v["stats"]
    add("## Data")
    add("")
    for k, val in stats.items():
        add(f"- **{k}:** {val}")
    add("")

    add("## Methodology")
    add("")
    add(v["methodology"])
    add("")
    add("---")
    add("")
    add(
        "_All output is probabilistic and evidence-bearing — never a "
        "definitive judgement about the account or person behind it._"
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# View helpers
# ---------------------------------------------------------------------------


_SEVERITY_RANK = {"high": 4, "elevated": 3, "moderate": 2, "info": 1}
_TIER_RANK = {"high": 4, "elevated": 3, "moderate": 2, "low": 1}


def _headline_cross_link(payload: dict) -> dict | None:
    links = payload.get("cross_links") or []
    if not links:
        return None
    sorted_links = sorted(
        links, key=lambda l: _SEVERITY_RANK.get(l.get("severity"), 0), reverse=True,
    )
    return sorted_links[0]


def _top_cross_links(payload: dict, *, n: int = 3) -> list[dict]:
    links = payload.get("cross_links") or []
    return sorted(
        links, key=lambda l: _SEVERITY_RANK.get(l.get("severity"), 0), reverse=True,
    )[:n]


#: Hard ceiling on the full account list in one report. Above the operator scan cap (150) so it is
#: never reached in practice; it exists so a pathological payload cannot produce an unbounded response.
_ALL_COMMENTERS_CAP = 250


def _all_commenters(payload: dict) -> list[dict[str, Any]]:
    """EVERY account this report scored, worst first, not just the flagged ones.

    Showing only flagged accounts made the report read as a hit list and hid the most reassuring
    thing in it: that most of the section came back clean. A reader who can see 240 low-tier rows
    understands the 12 elevated ones as a finding rather than as the product flagging everything.

    Deliberately LIGHTER than ``_flagged_commenters``: no ``reasons`` and no ``recent_activity``. Those
    are per-account evidence blobs, and carrying them for every account would multiply the public
    response by the size of the whole comment section for data the table never renders.
    """
    video = payload.get("video") or {}
    rows = [c for c in (video.get("commenters") or []) if isinstance(c, dict)]
    rows.sort(
        key=lambda c: (
            _TIER_RANK.get(c.get("tier"), 0),
            c.get("coordination_adjusted_probability") or c.get("overall_probability") or 0,
        ),
        reverse=True,
    )
    return [
        {
            "handle": c.get("handle"),
            "external_id": c.get("external_id"),
            "tier": c.get("tier") or "low",
            "overall_probability": (
                c.get("coordination_adjusted_probability") or c.get("overall_probability") or 0
            ),
            "intent_label": c.get("intent_label"),
        }
        for c in rows[:_ALL_COMMENTERS_CAP]
    ]


def _flagged_commenters(payload: dict) -> list[dict[str, Any]]:
    video = payload.get("video") or {}
    commenters = video.get("commenters") or []
    flagged = [c for c in commenters if c.get("tier") in ("moderate", "elevated", "high")]
    flagged.sort(
        key=lambda c: (
            _TIER_RANK.get(c.get("tier"), 0),
            c.get("coordination_adjusted_probability") or c.get("overall_probability") or 0,
        ),
        reverse=True,
    )
    # Strip heavy fields for the report (recent_activity already trimmed at scan time).
    return [
        {
            "handle": c.get("handle"),
            "external_id": c.get("external_id"),
            "tier": c.get("tier"),
            "overall_probability": c.get("coordination_adjusted_probability") or c.get("overall_probability") or 0,
            "intent_label": c.get("intent_label"),
            "summary": c.get("summary"),
            "reasons": c.get("reasons") or [],
            "recent_activity": c.get("recent_activity") or [],
        }
        for c in flagged
    ]


def _summarize_focus_account(fa: dict | None) -> dict | None:
    if not fa:
        return None
    return {
        "handle": fa.get("handle"),
        "external_id": fa.get("external_id"),
        "tier": fa.get("tier"),
        "overall_probability": fa.get("overall_probability") or 0,
        "summary": fa.get("summary"),
        "intent_label": fa.get("intent_label"),
        "reasons": fa.get("reasons") or [],
    }


def _summarize_video(video: dict | None, template: Template) -> dict | None:
    if not video:
        return None
    return {
        "video_id": video.get("video_id"),
        "commenter_count": video.get("commenter_count", 0),
        "fresh_count": video.get("fresh_count", 0),
        "cached_count": video.get("cached_count", 0),
        "tier_distribution": video.get("tier_distribution") or {},
        "coordination_score": video.get("coordination_score") or 0,
        "coordination_tier": video.get("coordination_tier") or "low",
        "thread_scan": video.get("thread_scan") or {},
        "cluster_count": len(video.get("clusters") or []),
        "high_suspicion_handles": (
            video.get("high_suspicion_handles") or []
            if template == "evidence"
            else (video.get("high_suspicion_handles") or [])[:15]
        ),
    }


def _scanned_count(payload: dict) -> int:
    """How many commenters this report actually scored.

    Prefers the recorded `commenter_count` and falls back to the length of the commenters list,
    because a payload carrying commenters but no count would otherwise render "0 of 312", which reads
    as a broken product rather than a partial report.
    """
    video = payload.get("video") or {}
    count = video.get("commenter_count")
    if isinstance(count, int) and count > 0:
        return count
    return len(video.get("commenters") or [])


def _stats_block(payload: dict, *, commenters_available: int | None = None) -> dict[str, Any]:
    video = payload.get("video") or {}
    scanned = _scanned_count(payload)
    out: dict[str, Any] = {
        "Commenters scanned": (
            f"{scanned} of {commenters_available}"
            if commenters_available and commenters_available > scanned
            else scanned
        ),
        "Fresh / cached": f"{video.get('fresh_count', 0)} / {video.get('cached_count', 0)}",
        "Cross-links detected": len(payload.get("cross_links") or []),
        "YouTube quota used": payload.get("quota_used", 0),
        "Coordination clusters": len(video.get("clusters") or []),
    }
    return out


def _methodology_note() -> str:
    return (
        "OMISPHERE scores every account on eight behavioural dimensions: posting rhythm, "
        "content repetition, machine-written prose, profile coherence, personal voice, "
        "engagement farming, account maturity, and history authenticity. Each account is judged "
        "on its own evidence, and a high score requires several independent indicators that "
        "converge, not one unusual-looking trait. Ordinary traits that are common among real "
        "people (a new account, few followers, a short comment) cannot on their own produce a "
        "high score. Every score is probabilistic and carries the evidence behind it, never a "
        "definitive judgement about the account or the person using it."
    )


def _iso(v: Any) -> str | None:
    if v is None:
        return None
    if isinstance(v, str):
        return v
    if isinstance(v, datetime):
        return v.isoformat()
    return str(v)
